title: Stress ball
hero_image: images/stress-banner.png
description: Use Scratch to create a stress ball that you can squash!
version: 4
listed: true
copyedit: true
last_tested: "2020-09-01"
steps:
  - title: Introduction
  - title: Add a Ball sprite
  - title: Draw a face
  - title: Squash it
  - title: Shrink it
  - title: Choose your own sound effect
  - title: Insert a backdrop
  - title: Reflection
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
  - title: Add more
  - title: What next?
